### ISSUE TITLE
Ubuntu for Ulefone Amor_6e

### ISSUE THREAD

**Issue by Peggysus** [ubports/installer-configs#122] opened 2021-08-28 13:37 UTC

**Comment by Peggysus** [comment] 2021-08-28 13:38
Configuration for Ulefone devices

**Comment by JamiKettunen** [comment] 2024-03-15 09:52
This issue is non-actionable and should be closed. There is no place to request ports since otherwise that place would be full of issues. Also this device doesn't even have kernel source publicly available according to https://xdaforums.com/t/ulefone-armor-6-custom-kernel-compile-no-source-available.4553091/ and since it's from pre-GKI era the device might as well be e-waste as you can't even run UT with a generic kernel while using vendor kernel modules. I suggest not supporting companies like this if you value being able to install a non-Android operating system.

Also #121 is a dupe of this same issue.

**Closed** 2024-03-15 10:20 UTC
